Jayus/Jayus/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
#common admin
#from django.contrib import admin
#custom admin
from JayusApp.admin import admin_site
# Esta bueno pero mas comeplejo.
# from robots_txt.views import RobotsTextView
from django.http import HttpResponse
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # Examples:
    # url(r'^blog/', include('blog.urls')),

    # admin
    url(r'^admin/', include(admin_site.urls)),
    #Admin site por defecto
    #url(r'^admin/', include(admin.site.urls)),
    #Login por defecto
    #url(r'^accounts/login/$', 'django.contrib.auth.views.login',
        #{'template_name': 'admin/login.html'}, name="my_login"),
    #Custom login
    url(r'^accounts/login/$', 'JayusApp.views.login_user'),
    # rich textbox
    url(r'^ckeditor/', include('ckeditor.urls')),
    # buscar
    url(r'^search/', include('haystack.urls')),
    #url(r'^buscar/get/', 'JayusApp.views.buscar'),

    # urls al home
    url(r'^$', 'JayusApp.views.home', name='home'),
    url(r'^/', 'JayusApp.views.home'),
    url(r'^home/', 'JayusApp.views.home'),
    url(r'^admin/logout/home/', 'JayusApp.views.logout_view'),

    # registrar/validar
    url(r'^registrar/', 'JayusApp.views.registrar'),
    url(r'^validar/(?P<id>[^/]+)', 'JayusApp.views.validar'),

    # funcionales
    url(r'^perfil/get/', 'JayusApp.views.redirectPerfil'),
    url(r'^perfil/edit', 'JayusApp.views.editPerfil'),
    url(r'^perfil/(?P<idPerfil>[^/]+)', 'JayusApp.views.perfilView'),
    url(r'^perfil/', 'JayusApp.views.perfilView'),
    url(r'^mis_comunidades/', 'JayusApp.views.mis_comunidades'),
    url(r'^comunidad/add', 'JayusApp.views.comunidad_add'),
    url(r'^comunidad/edit/(?P<idComunidad>[0-9]+)', 'JayusApp.views.comunidad_edit'),
    url(r'^comunidad/delete/(?P<idComunidad>[0-9]+)', 'JayusApp.views.comunidad_delete'),
    url(r'^comunidad/miembros/eliminar/(?P<idPerfil>[0-9]+)/(?P<idComunidad>[0-9]+)',
            'JayusApp.views.eliminar_miembro'),
    #TODO: Revisar. Los redirects más que nada
    url(r'^comunidad/miembros/(?P<idComunidad>[0-9]+)',
                'JayusApp.views.comunidad_miembros'),
    url(r'^comunidad/(?P<idComunidad>[^/]+)', 'JayusApp.views.comunidad'),
    #url(r'^robots.txt$', RobotsTextView.as_view()),
    #Bien sencillito (http://fredericiana.com/2010/06/09/three-ways-to-add-a-robots-txt-to-your-django-project/)
    url(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")),
    # statics
    url(r'^aboutUs/', 'JayusApp.views.aboutUs'),
    url(r'^gracias/', 'JayusApp.views.gracias'),

    # contenido
     url(r'^contenido/modificar/(?P<idContenido>[0-9]+)',
                'JayusApp.views.modificar_contenido'),
    url(r'^contenido/(?P<idContenido>[0-9]+)', 'JayusApp.views.contenido'),
    url(r'^contenido/eliminar/(?P<idContenido>[0-9]+)',
                'JayusApp.views.eliminar_contenido'),
    url(r'^comentario/eliminar/(?P<idDetalleContenido>[0-9]+)/(?P<idContenido>[0-9]+)',
                'JayusApp.views.eliminar_comentario'),
    #TODO: Revisar. Los redirects más que nada
    url(r'^contenido/add/(?P<lugar>\w+)/(?P<idLugar>\w+)',
                'JayusApp.views.contenido_add'),
    #TODO: Revisar. Los redirects más que nada
    url(r'^contenido/add/',
                'JayusApp.views.contenido_sin_params'),
    url(r'^denunciar/', 'JayusApp.views.denunciar'),
    #TODO: Revisar. Los redirects más que nada
    url(r'^comentario/add/(?P<idContenido>[0-9]+)',
                'JayusApp.views.alta_comentario'),
    #TODO: Revisar. Los redirects más que nada
    url(r'^contenido/valorar/(?P<idContenido>[0-9]+)/(?P<p_tipo_contenido>[0-9]+)',
                'JayusApp.views.valorar_contenido'),
    url(r'^autor/(?P<idContenido>[0-9]+)', 'JayusApp.views.autor'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#Para manajar un 404 y un 500
handler404 = 'JayusApp.views.error404'
handler500 = 'JayusApp.views.error500'

Jayus/JayusApp/models.py
# -*- coding: utf-8 -*-
from django.db import models
import uuid
from django.utils import timezone
from django.contrib.auth.models import Group
#from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from JayusApp.Common.Enum import SexoEnum, VisibilidadEnum, TipoContenidoEnum
from JayusApp.Common.Enum import EstadoContenidoEnum, EstadoPerfilEnum
from JayusApp.Common.Enum import RolMiembroEnum
# TODO: https://docs.djangoproject.com/en/1.8/topics/auth/default/#topic-authorization


class MyUserManager(BaseUserManager):
    def create_user(self, username, email, password):
        if not username:
            raise ValueError('Se requiere nombre de usuario')

        if not email:
            raise ValueError('Se requiere email')

        if not password:
            raise ValueError('Se requiere contraseña')

        user = self.model(
            username=username,
            email=self.normalize_email(email)
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password):
        user = self.create_user(username, email,
            password=password
        )
        user.is_active = True
        user.is_admin = True
        user.save(using=self._db)
        return user


class CustomUser(AbstractBaseUser):
    username = models.CharField(max_length=50,
        verbose_name='Nombre de usuario',
        unique=True)
    email = models.EmailField(
        verbose_name='Correo electrónico',
        max_length=100
    )
    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def get_full_name(self):
        # The user is identified by their email address
        return self.username

    def get_short_name(self):
        # The user is identified by their email address
        return self.username

    def __str__(self):              # __unicode__ on Python 2
        return self.username

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_active

# Create your models here.


class RegistrosPendientes(models.Model):
    token = models.CharField(max_length=64, verbose_name="Activation key",
                                default=uuid.uuid1)
    usuario_modificacion = models.ForeignKey(CustomUser, null=True,
                                            blank=True)
    fecha_generacion = models.DateField(default=timezone.now)
    es_valido = models.BooleanField(default=True)


class auditoriaField(models.Model):
    fecha_modificacion = models.DateTimeField(default=timezone.now)
    usuario_modificacion = models.CharField(max_length=100, null=True,
                                            blank=True)
    # Está clase usa herencia para las tablas que necesitan auditoria.
    # No construye ninguna clase, pero las que la heredan tienen estos campos

    class Meta:
        abstract = True


class eliminarField(models.Model):
    fecha_baja = models.DateField(null=True, blank=True)
    usuario_baja = models.CharField(max_length=100, null=True,
                                            blank=True)

    class Meta:
        abstract = True


class Perfil(models.Model):
    usuario = models.OneToOneField(CustomUser)
    imagen = models.ImageField(null=False, upload_to = "perfiles/%Y/%m/%d",
                    default="http://localhost:8000/static/img/users.png")
    nombre = models.CharField(max_length=100, null=True, blank=True)
    apellido = models.CharField(max_length=100, null=True, blank=True)
    fechaNacimiento = models.DateField(null=True, blank=True)
    sexo = models.CharField(max_length=1, choices=SexoEnum.choices(),
                        null=True, blank=True)
    localidad = models.CharField(blank=True, max_length=30)
    provincia = models.CharField(blank=True, max_length=30)
    pais = models.CharField(blank=True, max_length=30)
    telefono = models.CharField(blank=True, max_length=30)
    groups = models.ForeignKey(Group, blank=True, null=True)
    puntuacion = models.DecimalField(max_digits=4, decimal_places=0, default=50)
    estado = models.CharField(max_length=1, choices=EstadoPerfilEnum.choices(),
                                default=EstadoPerfilEnum.Activo.value)

    def __str__(self):
        # Ver si no hay nombre/apellido entonces user name
        return (self.usuario.username)

    def save(self, *args, **kwargs):
        if not self.usuario:
            raise ValueError('Se requiere usuario')

        # Saving the object with the default save() function
        super(Perfil, self).save(*args, **kwargs)


class Comunidad(eliminarField):
    nombre = models.CharField(max_length=80)
    descripcion = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.nombre


class Miembro(auditoriaField, eliminarField):
    comunidad = models.ForeignKey(Comunidad, null=False, blank=False)
    usuario = models.ForeignKey(CustomUser, null=False, blank=False)
    rol = models.CharField(max_length=1, choices=RolMiembroEnum.choices(),
                                default=RolMiembroEnum.Publicador.value)

    def __str__(self):
        return self.usuario.username


class Contenido(auditoriaField, eliminarField):
    titulo = models.CharField(max_length=100)
    contenido = RichTextField()
    estado = models.CharField(max_length=1,
                            choices=EstadoContenidoEnum.choices(),
                            default=EstadoContenidoEnum.Activo.value)
    visibilidad = models.CharField(max_length=1,
                            choices=VisibilidadEnum.choices(),
                            default=VisibilidadEnum.Privado.value)
    comunidad = models.ForeignKey(Comunidad, null=True, blank=True)
    usuario = models.ForeignKey(CustomUser, null=True, blank=True,
                related_name='usuario_creador_contenido')
    puntuacion = models.DecimalField(max_digits=4, decimal_places=0, default=0)


class DetalleContenido(auditoriaField, eliminarField):
    contenido = models.ForeignKey(Contenido, null=False, blank=False)
    descripcion = models.CharField(max_length=250)
    usuario = models.ForeignKey(CustomUser, null=False,
                related_name='usuario_creador_detalle')
    tipo_contenido = models.CharField(max_length=1,
                                    choices=TipoContenidoEnum.choices(),
                                    default=TipoContenidoEnum.Comentario.value)


class Denuncia(auditoriaField, eliminarField):
    tipo = models.CharField(max_length=50)
    idObjeto = models.IntegerField()
    razon = models.CharField(max_length=200, blank=True, null=True)
    # En auditoria estaria quien lo denuncio
    # En eliminar field, cuando se elimina 'contenido' entonces lo doy de baja

Jayus/JayusApp/forms/commentForm.py
# -*- coding: utf-8 -*-
from django import forms
from JayusApp.models import Contenido, DetalleContenido


class NewCommentForm(forms.ModelForm):
    descripcion = forms.CharField(widget=forms.Textarea, label='Comentario',
                        max_length=250, required=True)

    class Meta:
        model = DetalleContenido
        fields = ('descripcion',)

    def clean_comment(self):
        # Chequea que el comentario no esté vacío
        comentario = self.cleaned_data.get("descripcion")

        if comentario != "":
            raise forms.ValidationError("No puede insertar un comentario vacío.")
        return comentario

Jayus/JayusApp/forms/comunidadForm.py
# -*- coding: utf-8 -*-
from django import forms
from JayusApp.models import Miembro, Comunidad, CustomUser
from JayusApp.Common.Enum import RolMiembroEnum

class MiembroForm(forms.ModelForm):
    usuario = forms.ModelChoiceField(required=True,
        widget=forms.Select(attrs={'class': 'form-control'}),
        queryset=CustomUser.objects.filter(is_active=True))
    rol = forms.ChoiceField(widget=forms.Select(attrs={'class': 'form-control'}),
            choices=RolMiembroEnum.choices(), required=True)

    class Meta:
        model = Miembro
        fields = ('usuario', 'rol')

class ComunidadForm(forms.ModelForm):
    nombre = forms.CharField(required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'}))
    descripcion = forms.CharField(required=True,
        widget=forms.Textarea(attrs={'class': 'form-control',
                                    'cols': 10, 'rows': 4}))

    class Meta:
        model = Comunidad
        fields = ('id', 'nombre', 'descripcion')

Jayus/JayusApp/forms/contenidoForm.py
# -*- coding: utf-8 -*-
from django import forms
from JayusApp.models import Contenido
from ckeditor.widgets import CKEditorWidget


class ContenidoForm(forms.ModelForm):
    titulo = forms.CharField(label='Título', max_length=100,
                        required=True)
    contenido = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Contenido
        fields = ('titulo', 'contenido', 'visibilidad')

Jayus/JayusApp/forms/perfilForm.py
# -*- coding: utf-8 -*-
from django import forms
from JayusApp.models import Perfil
from JayusApp.Common.Enum import SexoEnum


class PerfilForm(forms.ModelForm):
    nombre = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    apellido  = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    localidad = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    fechaNacimiento = forms.DateField(required=False,
            widget=forms.TextInput(attrs={'class': 'form-control datepicker'}))
    sexo = forms.ChoiceField(widget=forms.Select(attrs={'class': 'form-control'}),
            choices=SexoEnum.choices(), required=False)
    provincia = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    pais = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    telefono = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    usuario = forms.HiddenInput()
    puntuacion = forms.HiddenInput()

    class Meta:
        model = Perfil
        fields = ('usuario', 'imagen', 'nombre', 'apellido', 'fechaNacimiento',
                'sexo', 'localidad', 'provincia', 'pais', 'telefono', 'puntuacion')

    def __init__(self, *args, **kwargs):
        super(PerfilForm, self).__init__(*args, **kwargs)
        # assign a (computed, I assume) default value to the choice field
        self.initial['sexo'] = 'Seleccione un valor'
        # you should NOT do this:
        #self.fields['sexo'].initial = 'Seleccione un valor'

Jayus/JayusApp/templates/_denunciar.html
    <div id="myModal" class="modal fade" tabindex="-1"
      role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <h4 class="modal-title" id="exampleModalLabel">Denunciando el contendio</h4>
          </div>
          <div class="modal-body">
            <label id="successful" style="display:none">Se ha registrado la denuncia.</label>
            <label id="error" style="display:none">Oops, ha ocurrido un error.</label>
            <div id="normal_body" class="container-fluid">
                <div class="row">
                  <input id="denunciar_tipo" style="display:none"></input>
                  <input id="denunciar_idObjeto" style="display:none"></input>
                </div>
                <div class="row">
                  <label><strong>Motivo:</strong></label>
                </div>
                <div class="row">
                  <textarea id="razon_denuncia" class="form-control"
                      rows="4" cols="50"></textarea>
                </div>
            </div>
          </div>
          <div class="modal-footer">
            <button id="btnSubmit" type="button" class="btn btn-primary"
                onclick="event_denuncia_click()">
                Denunciar
            </button>
            <button id="btnCancel" type="button" class="btn btn-default"
                data-dismiss="modal" onclick="event_restablecer_modal()">
                Cerrar
                </button>
          </div>
        </div>
      </div>
    </div>

    <script type="text/javascript" src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script type="text/javascript" src="http://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>

    <script>
      function event_restablecer_modal() {
            $('#error').css('display','none')
            $('#successful').css('display','none')
            $('#normal_body').css('display','')
            $('#razon_denuncia').val('')
            $('#btnSubmit').css('display','');
          }

      function event_denuncia_click() {
          $.ajax({
              url: {% url 'JayusApp.views.denunciar' %},
              type: 'POST',
              data: {
                  "tipo": $('#denunciar_tipo').val(),
                  "idObjeto": $('#denunciar_idObjeto').val(),
                  "razon": $('#razon_denuncia').val()
              },
          }).success(function (result) {
            $('#error').css('display','none')
            $('#successful').css('display','')
            $('#normal_body').css('display','none')
            $('#btnSubmit').css('display','none');
          }).error(function(result){
            $('#error').css('display','')
            $('#successful').css('display','none')
            $('#normal_body').css('display','none')
            $('#btnSubmit').css('display','none');
          });
      }
    </script>

Jayus/JayusApp/templates/_pre-contenido.html
<div class="panel panel-default">
      <div class="panel-heading" style="background-color:#FFFFFF;">
          <div class="row">
              <div class="col-md-8">
                  <a href="{% url 'JayusApp.views.contenido' contenido.id%}">
                    <h3 class="panel-title">{{ contenido.titulo|safe }}</h3>
                  </a>
              </div>
              <div class="col-md-4" style="text-align:right">
                    {{contenido.puntuacion}} punto{{contenido.puntuacion|pluralize}}
              </div>
          </div>
      </div>
      <div class="panel-body">
          <a href="{% url 'JayusApp.views.contenido' contenido.id%}">
            {{contenido.contenido|safe|truncatewords_html:15}}
          </a>
      </div>
  <div class="panel-footer" style="background-color:#FFFFFF;">
      <div class="row">
          <div class="col-md-4">
            {% if contenido.comunidad.id > 0 %}
                  Comunidad: {{contenido.comunidad}}
            {% endif %}
          </div>
          <div class="col-md-8" style="text-align:right">
             {% if contenido.usuario_modificacion  %}
                <strong>
                  <a href="{% url 'JayusApp.views.redirectPerfil' %}?username={{ contenido.usuario_modificacion }}">
                      {{ contenido.usuario_modificacion }}
                  </a>
                </strong>
                ||
             {% endif %}
              {{contenido.fecha_modificacion|date:"d/m/Y H:i"}}
          </div>
      </div>
  </div>
</div>

Jayus/JayusApp/templates/aboutUs.html
{% extends "base_sitio.html" %}
{% load staticfiles %}

{% block contenido%}
    <h1>Sobre Nosotros</h1>
    <hr>

    <div class="row" style="text-align:center">
        <div class="col-sm-4">
            <div class="row">
                <img src="../static/img/Lucas.jpg" class="foto-perfil">
            </div>
            <div class="row">
                <b>Lucas Betolini</b>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="row">
                <img src="../static/img/Nati.jpg" class="foto-perfil">
            </div>
            <div class="row">
                <b>Natalí Vargas</b>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="row">
                <img src="../static/img/Mariano.jpg" class="foto-perfil">
            </div>
            <div class="row">
                <b>Mariano Schaberger</b>
            </div>
        </div>
    </div>
    <div class="row" style="padding:2%">
        <br>
        <p>Con la expectativa de poder crear
        un software sencillo y práctico, que pueda
        de una manera simple incorporarse y ponerse
        en funcionamiento, es que surge Jayus.</p>
        <br>
        <p>El sistema fue desarrollado inicialmente
        para cumplir con obligaciones universitarias,
        luego dimos cuenta de sus potenciales
        posibilidades de competir en el mercado de
        los gestores de contenido, principalmente
        por dos ventajas fundamentales:</p>
        <ui>
        <li><b>Simpleza</b>, se busca no tener una gran cantidad
        de opciones y configuraciones que
        distraigan a los usuarios.</li>
        <li><b>Libertad</b>, para permitir a los usuarios
        tomar el código, usarlo y modificarlo a
        gusto.</li>
        <br>
        <p>Primordialmente buscamos poder crecer
        en este mercado apuntando y basando
        nuestro desarrollo para contribuir a
        pequeñas y medianas empresas.</p>
        <br>
        <p>Por último queremos informarles que
        pueden contactarse con nosotros a través
        de la dirección de correo electrónico:
        Jayus@hotmail.com</p>
    </div>

{% endblock %}

Jayus/JayusApp/templates/alta_comentario.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "css/jayusStyle.css" %}" />

<div class="comentario">
    <form action="{% url 'JayusApp.views.alta_comentario' idContenido%}" method="post">
        {% csrf_token %}
        <div class="row">
            <textarea class="nuevo-comentario" rows="5" id="id_descripcion"
            name="descripcion" type="text" placeholder="Comentar..." required></textarea>
        </div>
        <div class="row">
            {{ formComentario.descripcion.errors }}
        </div>

        <div class="row">
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        </div>
        <div class="row" style="padding:2%">
            <button class="btn btn-primary" type="submit">Comentar</button>
        </div>
    </form>
</div>

Jayus/JayusApp/templates/comunidad_abm.html
{% extends "base_sitio.html" %}
{% load staticfiles %}

{% block title %} Jayus | {{titulo}} {% endblock %}


{% block extrastyle %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static "css/jayusStyle.css" %}" />
{% endblock %}

{% block contenido %}
    <div class="fluid-container" style="margin-left:auto; margin-right:auto; width:60%">
        <form id="comunidadForm" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="row">
                <center>
                    <h4>
                        {{titulo}}
                        {% if comunidadId %}
                            {{ comunidad.nombre.value }}
                        {% endif %}
                    </h4>
                </center>
            </div>

            <input id="id_comunidad" type="text" value='{{comunidadId}}' style="opacity: 0"/>

            <div class="form-group">
                <label for="id_nombre">Nombre</label>
                {{ comunidad.nombre }}
            </div>
            <div class="row validacion" id="errorNombre" style="padding-left: 3%; padding-bottom: 2%; color: red;"></div>

            <div class="form-group">
                <label for="id_descripcion">Descripción</label>
                {{ comunidad.descripcion }}
            </div>
            <div class="row validacion" id="errorDescripcion" style="padding-left: 3%; padding-bottom: 2%; color: red;"></div>

            <table id="tabla_miembros" class="table">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Usuario</th>
                  <th>Rol</th>
                  <th>
                      <button id="btnAddRow" class="btn btn-default"
                          title="Agregar" type="button"
                          data-toggle="modal" data-target="#myModal"
                          onclick="inicializar_cmb()">
                          +
                      </button>
                  </th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>1</th>
                  <td id="id_user_1" name="user_1">{{request.user.username}}</td>
                  <td id="id_rol_1" name="rol_1">Lider</td>
                  <td></td>
                </tr>
                  {% if miembros %}
                      {% for m in miembros %}
                          {% if m.0 != request.user.username %}
                            <tr>
                                  <th>{{ iterator.next|add:"2" }}</th>
                                  <td>{{ m.0 }}</td>
                                  <td>{{ m.1 }}</td>
                                  <td>
                                      <button class='btn btn-default' title='Eliminar' onclick='this.parentNode.parentNode.remove();'> X </button>
                                  </td>
                            </tr>
                          {% endif %}
                      {% endfor %}
                  {% endif %}
              </tbody>
            </table>

            <div class="row validacion" id="errorGeneral" style="padding-left: 3%; padding-bottom: 2%; color: red;"></div>

            <center class="row" style="padding:2%">
                {% if comunidadId %}
                    <button class="btn btn-primary" type="button" onclick="editar_click()">Guardar</button>
                {% else %}
                    <button class="btn btn-primary" type="button" onclick="guardar_click()">Guardar</button>
                {% endif %}
                <a class="btn btn-default" href="{% url 'JayusApp.views.home' %}"">Cancelar </a>
            </center>
        </form>
    </div>
    {% include "comunidad_abm_miembros.html" %}
{% endblock %}

Jayus/JayusApp/templates/registrar_user.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static bootstrap_admin_template_tags %}
{% load staticfiles %}

{% block extrastyle %}

{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/login.css" %}" />{% endblock %}
    {% block bodyclass %}
        {{ block.super }} login
    {% endblock %}
{% block nav-global %}

{% endblock %}

{% block branding %}{% endblock %}

{% block content_title %}{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block sidebar_menu %}{% endblock %}

{% block content_container %}

<center style="width:30%; margin: 0 auto !important;">
    <div class="panel panel-primary" style="padding:2%">
      <center>
            <img src="/static/img/jayus-registro.gif" style="width: 100%;">
        </center><br>
      <div class="panel-body">
        <form action="{% url 'JayusApp.views.registrar' %}" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                    <label for="id_username">Usuario</label>
                </div>
                <div class="col-md-6">
                    {{ form.username }}
                </div>
            </div>
            <div class="row">
                {{ form.username.errors }}
            </div>
            <div class="row">
                <div class="col-md-6">
                    <label for="id_email">Email</label>
                </div>
                <div class="col-md-6">
                    {{ form.email }}
                </div>
            </div>
            <div class="row">
                {{ form.email.errors }}
            </div>
            <div class="row">
                <div class="col-md-6">
                    <label for="id_password1">Contraseña</label>
                </div>
                <div class="col-md-6">
                    {{ form.password1 }}
                </div>
            </div>
            <div class="row">
                {{ form.password1.errors }}
            </div>
            <div class="row">
                <div class="col-md-6">
                    <label for="id_password2">Repetir contraseña</label>
                </div>
                <div class="col-md-6">
                    {{ form.password2}}
                </div>
            </div>
            <div class="row">
                {{ form.password2.errors }}
            </div>

            <div class="row">
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            </div>

            <div class="row" style="padding:2%">
                <button class="btn btn-primary" type="submit">Registrar</button>
                <a class="btn btn-default" href="{% url 'JayusApp.views.home' %}"">Cancelar </a>
            </div>
        </form>
      </div>
    </div>
</center>
{% endblock %}